[project]
author = "SET SOPHY"
author-email = "phyrakset007@gmail.com"
name = "langchain-langgraph-and-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
